# Generated by Django 3.1 on 2020-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0017_auto_20200820_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
