image: archlinux
packages:
  - docker
sources:
  - https://git.sr.ht/~crocmagnon/blog
secrets:
  - 2da6ddc6-3d12-4306-a1e4-8268c6194386
  - 29bc352f-0807-46e9-a4ef-2f869f94afa3
  - 5c948915-48c2-4542-8fc1-a5676f4d7126
environment:
  TESTING: true
  BLOG_TESTS: rg.fr-par.scw.cloud/crocmagnon/blog:tests
  BLOG_LATEST: rg.fr-par.scw.cloud/crocmagnon/blog:latest
tasks:
  - setup_docker: |
      ./blog/docker/setup-docker
  - build_and_test: |
      docker login -u crocmagnon --password-stdin < .docker-secret
      cd blog
      docker pull $BLOG_IMAGE || true
      docker build --pull --cache-from $BLOG_LATEST -t $BLOG_LATEST -f Dockerfile .
      docker build -t $BLOG_TESTS -f tests.Dockerfile .
      docker run --rm -t $BLOG_TESTS /app/docker/runtests.sh
      docker push $BLOG_LATEST
  - deploy: |
      ssh blog -o StrictHostKeyChecking=no "/srv/blog/redeploy"
triggers:
  - action: email
    condition: failure
    to: Gabriel Augendre <gabriel@augendre.info>
