image: archlinux
packages:
  - docker
  - docker-compose
sources:
  - https://git.sr.ht/~crocmagnon/blog
secrets:
  - 2da6ddc6-3d12-4306-a1e4-8268c6194386
  - 29bc352f-0807-46e9-a4ef-2f869f94afa3
  - 5c948915-48c2-4542-8fc1-a5676f4d7126
environment:
  TESTING: true
tasks:
  - setup_docker: |
      ./blog/docker/setup-docker
  - build_and_test: |
      docker login -u crocmagnon --password-stdin < .docker-secret
      cd blog
      docker-compose pull django tests || true
      docker-compose build --pull django
      docker-compose build tests
      docker-compose run tests
      docker-compose push django tests
  - deploy: |
      ssh blog -o StrictHostKeyChecking=no "/srv/blog/redeploy"
triggers:
  - action: email
    condition: failure
    to: Gabriel Augendre <gabriel@augendre.info>
