stages:
  - build
  - test
  - publish
  - deploy


deploy:
  stage: deploy
  image: ubuntu
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y --no-install-recommends )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/config
    - chmod 644 ~/.ssh/config
    - echo "$SSH_CONFIG" > ~/.ssh/config
  script:
    - ssh blog -o StrictHostKeyChecking=no "/home/gaugendre/blog/update"
  only:
    - master
