exclude: (\.min\.(js|css)(\.map)?$|/vendor/)
ci:
  skip: [mypy]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - -t
          - py310
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.11.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.0
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-annotations-complexity
          - flake8-builtins
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-noqa
          - flake8-pytest-style
          - flake8-pyi
          - wemake-python-styleguide
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        types_or: [javascript, css]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        args: [--fix]
        types_or: [javascript, css]
        additional_dependencies:
          - eslint
          - eslint-config-prettier
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or: [python, pyi]
