exclude: (\.min\.(js|css)(\.map)?$|/vendor/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.4.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]
  - repo: https://github.com/rtts/djhtml
    rev: v1.4.10
    hooks:
      - id: djhtml
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-noqa
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-pytest-style
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [javascript, css]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.4.1
    hooks:
      - id: eslint
        args: [--fix]
        types_or: [javascript, css]
        additional_dependencies:
          - eslint@^7.29.0
          - eslint-config-prettier@^8.3.0
