version: '2.4'
services:
  django:
    image: rg.fr-par.scw.cloud/crocmagnon/blog:latest
    build:
      context: .
      args:
        POETRY_OPTIONS: "--no-dev"
    env_file:
      - .env
    volumes:
      - ./db:/db
      - staticfiles:/app/staticfiles
      - media:/app/media
    restart: on-failure
    init: true
    tty: true
  nginx:
    image: nginx:1.19.2
    ports:
      - 8000:80
    volumes:
      - staticfiles:/app/static
      - media:/app/media
      - ./docker/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

volumes:
  staticfiles: {}
  media: {}
