version: '2.4'
services:
  django:
    image: crocmagnon/blog:latest
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./db:/db
      - ./static:/app/staticfiles
    restart: on-failure
  tests:
    image: crocmagnon/blog:tests
    build:
      context: .
      dockerfile: tests.Dockerfile
