version: '2.4'
services:
  django:
    image: crocmagnon/blog:dev
    build:
      context: .
      args:
        POETRY_OPTIONS: "--no-dev"
    env_file:
      - envs/local.env
    volumes:
      - ./db:/db
      - staticfiles:/app/staticfiles
      - media:/app/media
    restart: on-failure
    init: true
    tty: true

volumes:
  staticfiles: {}
  media: {}
