[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
DJANGO_SETTINGS_MODULE = "blog.settings"
testpaths = [
    "articles",
    "blog",
    "attachments",
]

[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["Gabriel Augendre <gabriel@augendre.info>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"
markdown = "^3.2"
gunicorn = "^20.0"
Pygments = "^2.6"
django-anymail = {version = "^7.2", extras = ["mailgun"]}
pillow = "^7.2"
django-cleanup = "^5.0"
requests = "^2.24"
html2text = "^2020.1.16"
django-assets = "^2.0"
cssmin = "^0.2.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.7"
pytest = "^6.0"
pytest-django = "^3.9"
model-bakery = "^1.1"
pytest-cov = "^2.10.1"
pytest-recording = "^0.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
