[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["Gabriel Augendre <gabriel@augendre.info>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.0"
markdown = "^3.2"
gunicorn = "^20.0"
Pygments = "^2.6"
django-anymail = {version = "^8.4", extras = ["mailgun"]}
pillow = "^8.4"
django-cleanup = "^5.0"
requests = "^2.24"
html2text = "^2020.1.16"
readtime = "^1.1.1"
pylibmc = "^1.6.1"
django-debug-toolbar = "^3.2"
whitenoise = {extras = ["brotli"], version = "^5.2.0"}
rcssmin = "^1.0.6"
django-csp = "^3.7"
django-two-factor-auth = {extras = ["phonenumberslite"], git = "https://github.com/Bouke/django-two-factor-auth.git", rev = "ffe4422e"}

[tool.poetry.dev-dependencies]
pre-commit = "^2.7"
pytest = "^6.0"
pytest-django = "^4.5"
model-bakery = "^1.1"
pytest-cov = "^3.0"
pytest-recording = "^0.12.0"
pytest-rerunfailures = "^10.2"
pytest-env = "^0.6.2"
poetry-deps-scanner = "^1.0.1"
invoke = "^1.6.0"

[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--color=yes"
minversion = "6.0"
DJANGO_SETTINGS_MODULE = "blog.settings"
testpaths = [
    "src",
]
env = [
    "GOATCOUNTER_DOMAIN=gc.gabnotes.org"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
