image: archlinux
packages:
  - docker
sources:
  - https://git.sr.ht/~crocmagnon/blog
secrets:
  - 388c4445-d732-440b-8ff5-fc5dfb46f04a  # Scaleway Docker registry password
  - 78118477-73c2-4805-a613-c7aab23c92a8  # SSH config for blog
  - 5c948915-48c2-4542-8fc1-a5676f4d7126  # Deploy SSH key
environment:
  TESTING: true
  DEPS_LATEST: rg.fr-par.scw.cloud/crocmagnon/blog:deps-latest
  BLOG_LATEST: rg.fr-par.scw.cloud/crocmagnon/blog:latest
tasks:
  - setup_docker: |
      ./blog/docker/setup-docker
  - build_and_test: |
      docker login rg.fr-par.scw.cloud/crocmagnon -u nologin --password-stdin < .docker-secret
      cd blog
      docker pull $BLOG_LATEST || true
      docker pull $DEPS_LATEST || true

      docker build --pull --target venv --cache-from $DEPS_LATEST -t $DEPS_LATEST .
      docker build --pull --target prod --cache-from $BLOG_LATEST --cache-from $DEPS_LATEST -t $BLOG_LATEST -f Dockerfile .
      docker run --rm -t $BLOG_LATEST /app/docker/runtests.sh

      docker push $BLOG_LATEST
      docker push $DEPS_LATEST
  - deploy: |
      ssh blog -o StrictHostKeyChecking=no "/home/gaugendre/blog/redeploy"
triggers:
  - action: email
    condition: failure
    to: Gabriel Augendre <gabriel@augendre.info>
