# Generated by Django 3.1 on 2020-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                default="designing-and-3d-printing-a-wall-mount-for-my-isp-modem",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
