# Generated by Django 3.1 on 2020-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page", options={"ordering": ["position", "-published_at"]}
        ),
        migrations.AddField(
            model_name="page", name="position", field=models.IntegerField(default=0)
        ),
    ]
