# Generated by Django 3.1 on 2020-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_auto_20200818_1829"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["created_at"]}
        ),
        migrations.AlterField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
