# Generated by Django 3.1 on 2020-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0013_auto_20200818_1912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Not mandatory, fill only if you want me to be able to contact you. It will never be displayed here nor shared with any third party.",
                max_length=254,
                null=True,
            ),
        ),
    ]
