# Generated by Django 3.1 on 2020-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0015_auto_20200818_2138"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_notified",
            field=models.BooleanField(default=False),
        ),
    ]
