# Generated by Django 3.1 on 2020-09-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0018_auto_20200821_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
