# Generated by Django 3.1.1 on 2020-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0021_auto_20201110_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
