# Generated by Django 3.1.3 on 2020-12-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0022_article_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="has_code",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
