# Generated by Django 3.1.3 on 2020-12-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0024_auto_20201224_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="custom_css",
            field=models.TextField(blank=True),
        ),
    ]
