# Generated by Django 3.1.5 on 2021-03-03 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0027_auto_20210303_1633"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="keywords",
        ),
    ]
