# Generated by Django 3.1.5 on 2021-03-03 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0028_remove_article_keywords"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
