# Generated by Django 3.1.5 on 2021-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0031_auto_20210306_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="articles.Tag"
            ),
        ),
    ]
