# Generated by Django 3.1 on 2020-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
