# Generated by Django 3.1 on 2020-09-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0003_auto_20200826_1843"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["description"]},
        ),
    ]
