# Generated by Django 3.1.1 on 2020-11-28 19:22

from django.db import migrations

import attachments.models


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0005_attachment_open_graph_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="original_file",
            field=attachments.models.AbsoluteUrlFileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="processed_file",
            field=attachments.models.AbsoluteUrlFileField(
                blank=True,
                null=True,
                upload_to="",
            ),
        ),
    ]
