# Generated by Django 3.1.3 on 2020-12-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0006_auto_20201128_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="open_graph_image",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
