# Generated by Django 4.1.1 on 2022-10-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0007_auto_20201201_1917"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
