# Generated by Django 4.1.1 on 2022-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0008_attachment_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="updated_at",
        ),
    ]
