from .result import Result

def of_text(text, wpm: int | None = ...) -> Result: ...
def of_html(html, wpm: int | None = ...) -> Result: ...
def of_markdown(markdown, wpm: int | None = ...) -> Result: ...
