from .result import Result

def of_text(text: str, wpm: int | None = ...) -> Result: ...
def of_html(html: str, wpm: int | None = ...) -> Result: ...
def of_markdown(markdown: str, wpm: int | None = ...) -> Result: ...
