# Generated by Django 3.1 on 2020-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0002_auto_20200826_1814"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment", old_name="file", new_name="original_file",
        ),
        migrations.RemoveField(model_name="attachment", name="processed",),
        migrations.AddField(
            model_name="attachment",
            name="processed_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
